import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { StoreProvider } from "@/components/providers/StoreProvider";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { CookiesProvider } from "next-client-cookies/server";
import HeaderDefault from "@/components/HeaderDefault";
import ClientTheme from "@/theme/ClientTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <StyledComponentsRegistry>
            <CookiesProvider>
              <ClientTheme>{children}</ClientTheme>
            </CookiesProvider>
          </StyledComponentsRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
